from __future__ import annotations

from datetime import timedelta
from typing import Any

from src.utils.time import now_utc, to_iso


def _post(
    post_id: str,
    brand: str,
    text: str,
    hours_ago: int,
    author_handle: str,
    followers: int,
    likes: int,
    reposts: int,
    replies: int,
    quotes: int,
    views: int,
    query: str,
    language: str = "en",
    bookmark_count: int | None = None,
    quoted_post_id: str | None = None,
) -> dict[str, Any]:
    created_at = now_utc() - timedelta(hours=hours_ago)
    return {
        "post_id": post_id,
        "url": f"https://x.com/{author_handle}/status/{post_id}",
        "text": text,
        "author_id": f"author-{author_handle}",
        "author_name": author_handle.replace("_", " ").title(),
        "author_handle": author_handle,
        "author_followers": followers,
        "author_verified": followers >= 50000,
        "created_at": to_iso(created_at),
        "collected_at": to_iso(now_utc()),
        "language": language,
        "like_count": likes,
        "repost_count": reposts,
        "reply_count": replies,
        "quote_count": quotes,
        "bookmark_count": bookmark_count,
        "view_count": views,
        "media": [],
        "links": [],
        "quoted_post_id": quoted_post_id,
        "reply_to_post_id": None,
        "source_provider": "sample",
        "query": query,
        "brand_candidate": brand,
    }


def build_sample_posts() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    joybuy_posts = [
        _post(
            "10001",
            "joybuy",
            "Still waiting for my Joybuy refund after 12 days. Support keeps saying the case is under review.",
            5,
            "marie_shoplog",
            4200,
            84,
            18,
            41,
            7,
            18600,
            "joybuy refund",
            bookmark_count=11,
        ),
        _post(
            "10002",
            "joybuy",
            "Same refund issue with Joybuy UK. The order was cancelled but the payment is still pending.",
            4,
            "uk_deals_watch",
            18300,
            142,
            32,
            55,
            13,
            41200,
            "joybuy uk refund",
            quoted_post_id="10001",
        ),
        _post(
            "10003",
            "joybuy",
            "JD.com / Joybuy Germany delivered my phone two days earlier than expected. Price was good too.",
            7,
            "techbuyer_de",
            9800,
            61,
            10,
            12,
            3,
            15200,
            "jd.com joybuy germany delivery",
            bookmark_count=18,
        ),
        _post(
            "10004",
            "joybuy",
            "Is Joybuy Netherlands legit? Tracking says delivered but I never got the parcel.",
            11,
            "nl_gadgethelp",
            2300,
            38,
            9,
            26,
            4,
            8300,
            "joybuy netherlands tracking",
        ),
        _post(
            "10005",
            "joybuy",
            "京东海外 Joybuy 的客服回复很慢，退款进度没有解释。",
            9,
            "cn_eu_shopper",
            1200,
            23,
            5,
            16,
            2,
            3900,
            "京东 Joybuy 退款",
            language="zh",
        ),
        _post(
            "10006",
            "joybuy",
            "Joybuy France promo code worked and delivery estimate looks reasonable. Curious if returns are easy.",
            3,
            "paris_dealnote",
            6400,
            49,
            7,
            11,
            1,
            9100,
            "joybuy france delivery",
            bookmark_count=9,
        ),
        _post(
            "10007",
            "joybuy",
            "A thread about Joybuy Belgium: low prices, but some people report slow customer service on returns.",
            2,
            "ecom_observer",
            65200,
            288,
            74,
            96,
            38,
            128000,
            "joybuy belgium customer service",
            bookmark_count=55,
        ),
        _post(
            "10008",
            "joybuy",
            "Joybuy Luxembourg order arrived with damaged packaging. Product seems ok but support should respond.",
            16,
            "lux_shopper",
            900,
            12,
            2,
            7,
            0,
            1100,
            "joybuy luxembourg damaged",
        ),
        _post(
            "10009",
            "joybuy",
            "JD overseas shopping is confusing. Is Joybuy the same checkout flow for EU customers?",
            6,
            "crossborder_q",
            3500,
            35,
            6,
            18,
            4,
            7200,
            "jd overseas shopping joybuy",
        ),
        _post(
            "10010",
            "joybuy",
            "I might switch from Temu to Joybuy if the Germany shipping stays this fast.",
            13,
            "dealhunter_eu",
            21200,
            96,
            24,
            33,
            9,
            37800,
            "temu joybuy germany shipping",
        ),
        _post(
            "10011",
            "joybuy",
            "Joybuy return page keeps timing out for me. Anyone else seeing this?",
            1,
            "returns_case",
            1500,
            29,
            4,
            19,
            3,
            5600,
            "joybuy return customer service",
        ),
        _post(
            "10012",
            "joybuy",
            "This Joybuy refund screenshot is spreading in my group chat. Not sure if it is real.",
            20,
            "dealroom_mod",
            38000,
            174,
            44,
            68,
            21,
            72000,
            "joybuy refund screenshot",
            bookmark_count=27,
        ),
    ]

    temu_posts = [
        _post(
            "20001",
            "temu",
            "Temu refund took longer than expected but the support chat finally solved it.",
            6,
            "budget_basket",
            8200,
            78,
            18,
            34,
            5,
            19200,
            "temu refund",
        ),
        _post(
            "20002",
            "temu",
            "Temu delivery in Germany is slower this week. Anyone else waiting?",
            4,
            "deals_de",
            14400,
            126,
            22,
            61,
            8,
            28400,
            "temu delivery germany",
        ),
        _post(
            "20003",
            "temu",
            "Another Temu fake discount thread. The same price shows up every week.",
            12,
            "consumer_watch_eu",
            70100,
            392,
            88,
            102,
            41,
            160000,
            "temu fake discount",
        ),
        _post(
            "20004",
            "temu",
            "Temu package arrived damaged, refund request opened.",
            8,
            "parcel_diary",
            2100,
            22,
            6,
            14,
            2,
            4100,
            "temu damaged refund",
        ),
        _post(
            "20005",
            "temu",
            "Temu customer service is surprisingly quick today.",
            3,
            "cheaptech_today",
            5600,
            45,
            7,
            9,
            1,
            6900,
            "temu customer service",
        ),
    ]
    return joybuy_posts, temu_posts
